theme: jekyll-theme-minimal
title: Georgios Giasemidis' homepage
author: Georgios Giasemidis
description: My personal web-space, keep an eye for updates
remote_theme: daattali/beautiful-jekyll


navbar-links:
  About Me: "aboutme"
  # Author's home: "https://giasemidis.github.io/"
  CV: "https://giasemidis.github.io/docs/GGiasemidis-CV.pdf"
  Publications: "publications"
  Medium Articles:
    - LV forecasting literature review: "https://g-giasemidis.medium.com/lessons-from-a-review-of-low-voltage-load-forecasting-methods-1379627e8f0c"
    - Euroleague shot charts: "https://g-giasemidis.medium.com/create-euroleague-shot-charts-in-python-7ba4aa574644"
    - ESPN NBA Fantasy: "https://g-giasemidis.medium.com/nba-fantasy-analytics-with-python-on-epsn-f03f10a60187"
  ESPN Fantasy APP: "https://espn-nba-fantasy.herokuapp.com/"

# avatar: photos/lego-scientist.jpg
# round-avatar: True

title-img: photos/my-photo-at-the-office-blurred.png

# --- Footer social media links --- #
social-network-links:
  email: g.giasemidis@gmail.com
  github: giasemidis
  medium: g-giasemidis
  linkedin: ggiasemidis
  google-scholar: citations?user=vVyWiE8AAAAJ
  twitter: g_giase
  instagram: g.giase
  youtube: channel/UCr7vIbsZST1LoOfx736iiGg

 # Select which social network share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  instagram: true
  medium: true

 # Excerpt word length - Truncate the excerpt of each post on the feed page to the specified number of words
excerpt_length: 50

# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: true

# Add a search button to the navbar
post_search: true

# Use giscus comments:
giscus:
  hostname: giscus.app # Replace with your giscus instance's hostname if self-hosting
  repository: giasemidis/giasemidis.github.io # GitHub username/repository eg. "daattali/beautiful-jekyll"
  repository-id: MDEwOlJlcG9zaXRvcnkzMTk0NTk2MDk= # ID of your repository, retrieve this info from https://giscus.app
  category: Q&A # Category name of your GitHub Discussion posts
  category-id: DIC_kwDOEwqRGc4CPOI5 # ID of your category, retrieve this info from https://giscus.app
  mapping: pathname
  reactions-enabled: 1
  emit-metadata: 0
  theme: light
  lang: en
  input-position: bottom

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# Fill in your Google Analytics ID to track your website using Google Analytics
google_analytics: "UA-229643177-1"

# Exclude these files from production site
# exclude:
#   - CHANGELOG.md
#   - CNAME
#   - Gemfile
#   - Gemfile.lock
#   - LICENSE
#   - README.md
#   - screenshot.png
#   - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
