theme: jekyll-theme-minimal
title: Georgios Giasemidis' homepage
author: Georgios Giasemidis
description: My personal web-space, keep an eye for updates
remote_theme: daattali/beautiful-jekyll


navbar-links:
  About Me: "aboutme"
  Medium:
    - Euroleague shot charts: "https://g-giasemidis.medium.com/create-euroleague-shot-charts-in-python-7ba4aa574644"
    - ESPN NBA Fantasy: "https://g-giasemidis.medium.com/nba-fantasy-analytics-with-python-on-epsn-f03f10a60187"
  Author's home: "https://giasemidis.github.io/"
  
avatar: photos/lego-scientist.jpg
round-avatar: True

title-img: photos/my-photo-at-the-office-blurred.png

# --- Footer social media links --- #
social-network-links:
  email: g.giasemidis@gmail.com
  github: giasemidis
  twitter: g_giase
  linkedin: ggiasemidis
  instagram: g.giase
  google-scholar: vVyWiE8AAAAJ&hl
 
 # Select which social network share links to show in posts
share-links-active:
  gihub: true
  twitter: true
  linkedin: true
  google-scholar: true
  instagram: false
  
# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"
