theme: jekyll-theme-minimal
title: Georgios Giasemidis' homepage
author: Georgios Giasemidis
description: My personal web-space, keep an eye for updates
remote_theme: daattali/beautiful-jekyll


navbar-links:
  About Me: "aboutme"
  Medium Articles:
    - Euroleague shot charts: "https://g-giasemidis.medium.com/create-euroleague-shot-charts-in-python-7ba4aa574644"
    - ESPN NBA Fantasy: "https://g-giasemidis.medium.com/nba-fantasy-analytics-with-python-on-epsn-f03f10a60187"
  Publications: "publications"
#   Author's home: "https://giasemidis.github.io/"
  
avatar: photos/lego-scientist.jpg
round-avatar: True

title-img: photos/my-photo-at-the-office-blurred.png

# --- Footer social media links --- #
social-network-links:
  email: g.giasemidis@gmail.com
  github: giasemidis
  linkedin: ggiasemidis
  google-scholar: citations?user=vVyWiE8AAAAJ
  twitter: g_giase
  instagram: g.giase
  youtube: channel/UCr7vIbsZST1LoOfx736iiGg
 
 # Select which social network share links to show in posts
share-links-active:
  gihub: true
  twitter: true
  linkedin: true
  google-scholar: true
  instagram: false
  youtube: true
 
 # Excerpt word length - Truncate the excerpt of each post on the feed page to the specified number of words
excerpt_length: 50

# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: true

# Add a search button to the navbar
post_search: true
  
# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"
